python train.py --experiment mbv3   \
               --subexperiment run0 \
               --dataset cifar100   \
               --lr 0.001 \
               --router_ver 4      \
               --router_ngf 64     \
               --router_k 3        \
               --transformer_ver_root 8\
               --transformer_ver 1   \
               --transformer_ngf 64  \
               --transformer_k 3     \
               --transformer_expansion_rate 2 \
               --solver_ver 4       \
               --batch_norm         \
               --maxdepth 8       \
               --batch-size 512   \
               --scheduler step_lr  \
               --criteria avg_valid_loss  \
               --epochs_patience 50 \
               --epochs_node 200  \
               --epochs_finetune 200 \
               --seed 0    \
               --num_workers 0 \
               --finetune_during_growth \
               --num-classes 100 \
               --augmentation_on